# Generated by Django 4.0.2 on 2022-05-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_start_time_questionsession_started_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionsession',
            unique_together={('questioner', 'guest')},
        ),
    ]
