# Generated by Django 4.0.2 on 2022-05-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_questionsession_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='question.guest')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionier')),
            ],
            options={
                'unique_together': {('questioner', 'guest')},
            },
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionguestsession'),
        ),
        migrations.DeleteModel(
            name='QuestionSession',
        ),
    ]
