# Generated by Django 3.2.9 on 2022-05-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_questionguestsession_alter_answerrecord_session_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionier',
            new_name='Questionnaire',
        ),
        migrations.RenameField(
            model_name='questionguestsession',
            old_name='questioner',
            new_name='questionnaire',
        ),
        migrations.AlterUniqueTogether(
            name='questionguestsession',
            unique_together={('questionnaire', 'guest')},
        ),
    ]
