# Generated by Django 3.2.9 on 2022-05-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20220512_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionier',
            new_name='questionnaire',
        ),
    ]
